### ISSUE TITLE
gtk.GtkWarning: could not open display

### ISSUE THREAD

**Issue by FabioNevesRezende** [nmap/nmap#1136]
When I try to run Zenmap as sudo it returns:

```
No protocol specified
No protocol specified
Traceback (most recent call last):
  File "/usr/bin/zenmap", line 181, in <module>
    import zenmapGUI.App
  File "/usr/lib/python2.7/site-packages/zenmapGUI/App.py", line 157, in <module>
    import gtk
  File "/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 69, in <module>
    _init()
  File "/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 57, in _init
    warnings.warn(str(e), _gtk.Warning)
gtk.GtkWarning: could not open display
```

And quits. It doesn't happen when I run it without sudo. 
Zenmap version: 7.60
Gnome (Gnome shell) 3.26
Running on ArchLinux

**Comment by dmiller-nmap** [comment]
Did you try running with `gksu` or a similar graphical sudo command? Zenmap comes with a script, `su-to-zenmap.sh`, which tries several different methods if they are available.

**Comment by FabioNevesRezende** [comment]
tried now. Both `gksu` and `su-to-zenmap `resulted in the same error

**Comment by dmiller-nmap** [comment]
Probably you have an environment problem; `sudo` is stripping the `DISPLAY` environment variable from the environment of programs it runs. Verify this by trying to run `sudo DISPLAY=$DISPLAY zenmap`. If it works, you can use `sudo visudo` to edit the `/etc/sudoers` file and add the line:

    Defaults env_keep+="DISPLAY"

which will make this the default. Reference: https://askubuntu.com/questions/414785/cant-open-gedit-as-root

**Comment by FabioNevesRezende** [comment]
Running `sudo DISPLAY=$DISPLAY zenmap` also resulted in the original error.

**Comment by wargreen** [comment]
I have the same issue on debian SID.
zenmap 7.70+dfsg1-3

**Comment by fictitiousexistence** [comment]
Running into the same issue. 
Has there been a fix yet:?

Thanks.

**Comment by daniejstriata** [comment]
I get this error on Oracle Linux 8:

zenmap 7.70SVN

```
Traceback (most recent call last):
  File "/usr/local/bin/zenmap", line 181, in <module>
    import zenmapGUI.App
  File "/usr/local/lib/python2.7/site-packages/zenmapGUI/App.py", line 157, in <module>
    import gtk
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 69, in <module>
    _init()
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 57, in _init
    warnings.warn(str(e), _gtk.Warning)
gtk.GtkWarning: could not open display
```
Installed packages:
```
platform-python-coverage-4.5.1-7.el8.x86_64
platform-python-pip-9.0.3-13.el8.noarch
platform-python-setuptools-39.2.0-4.el8.noarch
policycoreutils-python-utils-2.8-16.1.0.1.el8.noarch
pygobject2-2.28.7-4.module+el8+5156+a8abff8b.x86_64
pygtk2-2.24.0-24.module+el8+5156+a8abff8b.x86_64
python2-2.7.15-24.0.1.module+el8.0.0+5335+79ff8c38.x86_64
python2-libs-2.7.15-24.0.1.module+el8.0.0+5335+79ff8c38.x86_64
python2-pip-9.0.3-13.module+el8.0.0+5335+79ff8c38.noarch
python2-setuptools-39.0.1-11.module+el8.0.0+5335+79ff8c38.noarch
python-srpm-macros-3-37.el8.noarch
snappy-1.1.7-5.el8.x86_64
```
Am I missing a package?

**Comment by daniejstriata** [comment]
Oh! It only happens when I use Wayland. Switched back to X11 Standard fixed this for me.

**Comment by fyodor** [comment]
Closing this as we haven't seen any reports of it since 2019.  If anyone is still having similar issues (the error would be much different now given our Python3 upgrade and such), please file a new issue.
