### ISSUE TITLE
ZenMap crashes on Mac OS - Image.py cant recognise icon file format

### ISSUE THREAD

**Issue by schliden** [nmap/nmap#1705]
Running Zenmap on Mac OS 10.11.6

Have tried running the GUI directly and opening from command line with sudo.

After running scan if I click on topology, ZenMap hangs then crashes.

Error Details: Unexpected error has crashed zenmap

Stack Trace

Version: 7.80
Traceback (most recent call last):
  File "/Applications/Zenmap.app/Contents/Resources/lib/python2.7/site-packages/radialnet/gui/RadialNet.py", line 885, in expose
    self.__draw(context)
  File "/Applications/Zenmap.app/Contents/Resources/lib/python2.7/site-packages/radialnet/gui/RadialNet.py", line 270, in check_graph_status
    return function(*args)
  File "/Applications/Zenmap.app/Contents/Resources/lib/python2.7/site-packages/radialnet/gui/RadialNet.py", line 1030, in __draw
    self.__draw_node(context, node)
  File "/Applications/Zenmap.app/Contents/Resources/lib/python2.7/site-packages/radialnet/gui/RadialNet.py", line 1174, in __draw_node
    icons.append(self.__icon.get_pixbuf('padlock'))
  File "/Applications/Zenmap.app/Contents/Resources/lib/python2.7/site-packages/radialnet/gui/Image.py", line 194, in get_pixbuf
    gtk.gdk.pixbuf_new_from_file(file)
GError: Couldn’t recognize the image file format for file “/Applications/Zenmap.app/Contents/MacOS/../Resources/share/zenmap/pixmaps/radialnet/padlock.png”

**Comment by Ponny035** [comment]
@schliden  Can you save data l already give full disk access to it and it still ask for permission

**Comment by Ponny035** [comment]
Also I test if I use quick scan it work fine

**Comment by schliden** [comment]
Ive tried running by double clicking the zenmap gui and from the command line using:

sudo /Applications/Zenmap.app/Contents/MacOS/zenmap.bin

It opens and scans using both approaches but freezes when I click on topology.

I have seen errors when shutting down that zenmap doesnt have permission to save to a settings file.

When zenmap runs it also deposits a file on the desktop called tmp.txt which contains:

en_AU.UTF-8
 | 
en_AU

**Comment by brianchin13** [comment]
I got the exactly same issue with schliden. Is there any fix yet ?

**Comment by Ponny035** [comment]
> I got the exactly same issue with schliden. Is there any fix yet ?

If you got error on save you can gain access full disk to zenmap and when you want to save it will occur same error you need to ignore and continue save it. These method work for me not sure for other environment

**Comment by brianchin13** [comment]
But i cant access to the topology after i scanned it crashes after i clicked on it. Other than that it works fine.

**Comment by schliden** [comment]
Rollback to ver 7.70 fixes the issue.

**Comment by brianchin13** [comment]
@schliden  It works perfectly! Thanks.

**Comment by Ponny035** [comment]
how can I fine 7.70 I click download on web it go to 7.8

**Comment by schliden** [comment]
https://nmap.org/dist/

https://nmap.org/dist/nmap-7.70.dmg

**Comment by Ponny035** [comment]
> Rollback to ver 7.70 fixes the issue.

7.70 is not comparable with macOS 10.15  so sad I will waiting for another update

**Comment by jbaker-dev** [comment]
> > Rollback to ver 7.70 fixes the issue.
> 
> 7.70 is not comparable with macOS 10.15 so sad I will waiting for another update

Having the same issue with zenmap 7.80 on macOS 10.15 Catalina

**Comment by dilmash** [comment]
Same here with zenmap 7.80 on Big Sur (11.2.3)

<img width="430" alt="image" src="https://user-images.githubusercontent.com/4518386/114681901-e01c8300-9d0e-11eb-821c-2799eba714cd.png">

Copy from the report window did work, therefore I added a screenshot here

**Comment by fyodor** [comment]
Thanks folks.  Closing as presumably fixed with latest Zenmap (or at least enough has changed that we would need a new report if anyone is seeing something similar).  We might have been failing to package the correct gdk pixbuf loader for PNG before, and I think it's built-in now. Topology viewer works for me with Nmap 7.99 on MacOS 26.5.1 (25F80).

**Comment by jbakerdev** [comment]
@fyodor Works for me with Nmap 7.99 on MacOS 15.7.4 (24G517)
