### ISSUE TITLE
Zenmap crash - missing import os in ScriptInterface.py

### ISSUE THREAD

**Issue by Stefan-mcp** [nmap/nmap#1949]
Version: 7.80SVN
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zenmapGUI/ScriptInterface.py", line 329, in script_list_timer_callback
    callback(True, process)
  File "/usr/local/lib/python2.7/dist-packages/zenmapGUI/ScriptInterface.py", line 338, in initial_script_list_cb
    if status and self.handle_initial_script_list_output(process):
  File "/usr/local/lib/python2.7/dist-packages/zenmapGUI/ScriptInterface.py", line 375, in handle_initial_script_list_output
    basename = os.path.basename(filename)
NameError: global name 'os' is not defined

seems resolved by adding the import into the file

**Comment by dmiller-nmap** [comment]
Duplicate of #2148
