### ISSUE TITLE
SVN post-commit hook error

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#1986]
The following call trace was listed by stock SVN client when committing r37919:
```
Warning: post-commit hook failed (exit code 1) with output:
Traceback (most recent call last):
  File "/admin/scripts/svn-mailer.py", line 1307, in <module>
    sys.argv[3:3+expected_args])
  File "/lib64/python2.7/site-packages/svn/core.py", line 307, in run_app
    return func(application_pool, *args, **kw)
  File "/admin/scripts/svn-mailer.py", line 77, in main
    messenger.generate()
  File "/admin/scripts/svn-mailer.py", line 367, in generate
    group, params, paths, subpool)
  File "/admin/scripts/svn-mailer.py", line 651, in generate_content
    renderer.render(data)
  File "/admin/scripts/svn-mailer.py", line 922, in render
    self._render_diffs(data.diffs, '')
  File "/admin/scripts/svn-mailer.py", line 963, in _render_diffs
    for diff in diffs:
  File "/admin/scripts/svn-mailer.py", line 808, in __getitem__
    src_fname, dst_fname = diff.get_files()
  File "/lib64/python2.7/site-packages/svn/fs.py", line 102, in get_files
    self._dump_contents(self.tempfile1, self.root1, self.path1)
  File "/lib64/python2.7/site-packages/svn/fs.py", line 87, in _dump_contents
    fp.write(chunk)
TypeError: must be unicode, not str
```
Possibly related, I have also noticed that recent commit emails no longer contain the actual diffs.

**Comment by dmiller-nmap** [comment]
I've edited `svn/fs.py` to change `"w+"` to `"wb"` as recommended in several message threads related to this bug. I'm not sure when it started or whether there will be a more permanent fix from the package maintainers, but this ought to keep us going for now. This issue can be closed when a SVN commit is successful without this message and with a diff in the commit email.

**Comment by nnposter** [comment]
The commit email for r37920 contains the diff.

**Comment by nnposter** [comment]
r37921 was a clean commit without errors; e-mail notice contains the diff
