### ISSUE TITLE
crash at open as root

### ISSUE THREAD

**Issue by lovezyou** [nmap/nmap#2020]
i will try to open as root but every time i get a crash error message .
![Screenshot from 2020-04-22 09-26-19](https://user-images.githubusercontent.com/50028865/79938958-91ca0080-847b-11ea-809e-318ffdea3b25.png)

**Comment by lovezyou** [comment]
Version: 7.80
Traceback (most recent call last):
  File "/usr/bin/zenmap", line 188, in <module>
    zenmapGUI.App.run()
  File "/usr/local/lib/python2.7/dist-packages/zenmapGUI/App.py", line 358, in run
    window = new_window()
  File "/usr/local/lib/python2.7/dist-packages/zenmapGUI/App.py", line 195, in new_window
    w = ScanWindow()
  File "/usr/local/lib/python2.7/dist-packages/zenmapGUI/MainWindow.py", line 212, in __init__
    self.scan_interface = ScanInterface()
  File "/usr/local/lib/python2.7/dist-packages/zenmapGUI/ScanInterface.py", line 211, in __init__
    self.__create_toolbar()
  File "/usr/local/lib/python2.7/dist-packages/zenmapGUI/ScanInterface.py", line 337, in __create_toolbar
    self.toolbar = ScanToolbar()
  File "/usr/local/lib/python2.7/dist-packages/zenmapGUI/ScanToolbar.py", line 178, in __init__
    self._create_profile()
  File "/usr/local/lib/python2.7/dist-packages/zenmapGUI/ScanToolbar.py", line 212, in _create_profile
    self.profile_entry = ProfileCombo()
  File "/usr/local/lib/python2.7/dist-packages/zenmapGUI/ProfileCombo.py", line 144, in __init__
    self.update()
  File "/usr/local/lib/python2.7/dist-packages/zenmapGUI/ProfileCombo.py", line 156, in update
    profile = CommandProfile()
  File "/usr/local/lib/python2.7/dist-packages/zenmapCore/UmitConf.py", line 426, in __init__
    Profile.__init__(self, user_profile)
  File "/usr/local/lib/python2.7/dist-packages/zenmapCore/UmitConf.py", line 266, in __init__
    user_profile = Path.scan_profile
  File "/usr/local/lib/python2.7/dist-packages/zenmapCore/Paths.py", line 231, in __getattr__
    join(self.user_config_dir, base_paths[name]))
  File "/usr/local/lib/python2.7/dist-packages/zenmapCore/Paths.py", line 289, in return_if_exists
    raise Exception("File '%s' does not exist or could not be found!" % path)
Exception: File '/root/.zenmap/scan_profile.usp' does not exist or could not be found!

**Comment by fyodor** [comment]
Thanks for the report.  This is probably resolved since we no longer even use Python2, but if anyone is still seeing something similar, please file a new issue.
