### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, exceptions.KeyError found

### ISSUE THREAD

**Issue by Jayr77** [nmap/nmap#2157]
** Describe the bug **
When trying to perform a scan or any action on nmap, it displays the message: "Version: 7.91
Traceback (most recent call last):
  File "zenmapGUI \ ScanInterface.pyo", line 389, in start_scan_cb
  File "zenmapGUI \ ScanInterface.pyo", line 516, in execute_command
TypeError: coercing to Unicode: need string or buffer, exceptions.KeyError found

When closing the message, the program is also closed

**Reproduce**
-Open the program
-Insert Target
-Choose the profile
-Click on Scan

**Expected behavior**
Features: Version: 7.91
Traceback (most recent call last):
  File "zenmapGUI \ ScanInterface.pyo", line 389, in start_scan_cb
  File "zenmapGUI \ ScanInterface.pyo", line 516, in execute_command
TypeError: coercing to Unicode: need string or buffer, exceptions.KeyError found

** Version information (please complete the following information): **
 - SO: Windous 7
-Nmap 7.91

** Additional context **
It also doesn't work on command.
[
![erro nmap](https://user-images.githubusercontent.com/72947518/96184629-21260d00-0f0f-11eb-975a-d15dd8f6592c.png)
](url)

**Comment by goarblt** [comment]
hello
https://www.evil.com/
