### ISSUE TITLE
Scanning times error 

### ISSUE THREAD

**Issue by Chinese-Cyq20100313** [nmap/nmap#2258]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, including window titles and command-line options.

**Expected behavior**

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]
 - Zenmap version from `Help` -> `About`
 - Output of `nmap --version`:

**Additional context**
Add any other context about the problem here, such as special network type.

`Version: 7.91
Traceback (most recent call last):
  File "zenmapGUI\ScanInterface.pyo", line 389, in start_scan_cb
  File "zenmapGUI\ScanInterface.pyo", line 516, in execute_command
TypeError: coercing to Unicode: need string or buffer, exceptions.UnicodeDecodeError found
`
Output upside

**Comment by goarblt** [comment]
hello
https://www.evil.com/
