### ISSUE TITLE
ZENMAP build error

### ISSUE THREAD

**Issue by vincenzogianfelice** [nmap/nmap#2714]
Debian 12 (x64, python3.11)

from command ```make install```

```
for f in `find nselib/data -name .svn -prune -o -type d -print`; do \
	/usr/bin/install -c -d /usr/local/share/nmap/$f; \
done
for f in `find nselib/data -name .svn -prune -o -type f -print`; do \
	/usr/bin/install -c -c -m 644 $f /usr/local/share/nmap/$f; \
done
/usr/bin/install -c -d /usr/local/bin /usr/local/share/man/man1
cd zenmap && /usr/bin/python3 setup.py --quiet install --prefix "/usr/local" --force 
/usr/lib/python3/dist-packages/setuptools/dist.py:548: UserWarning: The version specified ('7.94SVN') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
Traceback (most recent call last):
  File "/opt/nmap/zenmap/setup.py", line 585, in <module>
    setup(**setup_args)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/nmap/zenmap/setup.py", line 181, in run
    install.run(self)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 709, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_scripts.py", line 21, in run
    self.run_command("egg_info")
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 219, in finalize_options
    parsed_version = parse_version(self.egg_version)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '7.94SVN'
make: *** [Makefile:372: install-zenmap] Errore 1
```

**Comment by MrZelly** [comment]
Same issue on Gentoo 2.14

**Comment by EddieClown** [comment]
exactly the same on Ubuntu 23.04

**Comment by kpeletidis** [comment]
Same issue on openSUSE Tumbleweed 20240124 (rolling release).

**Comment by adamallaf** [comment]
I temporarily removed `"SVN"` locally from `VERSION` in `zenmap/zenmapCore/Version.py` and the compilation went through.

**Comment by dmiller-nmap** [comment]
This warning was made into an error in setuptools 69.0.0, November 2023:
* https://github.com/pypa/setuptools/pull/4066
* https://setuptools.pypa.io/en/latest/history.html#v69-0-0

We will work on a possible fix for the next release, though release versions do not use the "SVN" suffix, which is reserved for the development branch.

**Comment by coculi** [comment]
2024년 2월 16일 (금) 오전 3:58, Daniel Miller ***@***.***>님이 작성:

**Comment by gorilagl** [comment]
after downgrading the setuptools still dont work ?

**Comment by witlo001** [comment]
If you only need Nmap (not Zenmap), you can skip building Zenmap:

./configure --without-zenmap
make
sudo make install

**Comment by ts200x** [comment]
I resolve this on Debian 12 by running 
sudo apt install python3-build 

Then ran sudo make 

Then due to the way Debian 12 works with python and pip I needed to run 
sudo python3 -m pip config set global.break-system-packages true

then I could run sudo make clean install 
builds clean with no errors at that point. 
zenmap then launches fine.
