### ISSUE TITLE
Zenmap 7.94-7.95 edit selected profile throw UnicodeDecodeError

### ISSUE THREAD

**Issue by MiFeng-super** [nmap/nmap#2754]
**Describe the bug**
I am using nmap. I need to modify the profile, but it didn't work out.

**To Reproduce**
Zenmap menu"Profile" ->  "Edit Selected Profile"

**Expected behavior**
I need to successfully modify the profile.

**Version info (please complete the following information):**
 - OS: Windows 11 23H2
 - Zenmap 7.94
 - Nmap version 7.94

**Additional context**
```
Version: 7.94
Traceback (most recent call last):
  File "C:\software\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScriptInterface.py", line 261, in script_list_timer_callback
    callback(True, process)
  File "C:\software\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScriptInterface.py", line 270, in initial_script_list_cb
    if status and self.handle_initial_script_list_output(process):
  File "C:\software\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScriptInterface.py", line 301, in handle_initial_script_list_output
    for entry in get_script_entries(
  File "C:\software\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\ScriptMetadata.py", line 423, in get_script_entries
    metadata = ScriptMetadata(scripts_dir, nselib_dir)
  File "C:\software\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\ScriptMetadata.py", line 286, in __init__
    self.construct_library_arguments()
  File "C:\software\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\ScriptMetadata.py", line 416, in construct_library_arguments
    self.library_arguments[libname] = self.get_script_args(filepath)
  File "C:\software\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\ScriptMetadata.py", line 362, in get_script_args
    args = ScriptMetadata.get_script_args_from_file(f)
  File "C:\software\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\ScriptMetadata.py", line 370, in get_script_args_from_file
    for tag_name, tag_text in nsedoc_tags_iter(f):
  File "C:\software\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\ScriptMetadata.py", line 232, in nsedoc_tags_iter
    for line in f:
  File "dist/zenmap-w64/mingw64/lib/python3.10/codecs.py", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode byte 0x93 in position 5665: No mapping for the Unicode character exists in the target code page.
```

**Comment by dmiller-nmap** [comment]
We believe this is resolved in c840e236cb43cfa57d2542a3fc3688807cc90387, which will be included in the next release of Nmap.

**Comment by dmiller-nmap** [comment]
Fixed in Nmap 7.97
