### ISSUE TITLE
Zenmap Installation errors (Debian 12(Bookworm), latest python and sufficent dependency)

### ISSUE THREAD

**Issue by TannerSchultz2006** [nmap/nmap#2779]
Zenmap installation from source error (setup.py)

I was unable to install the entire set of packages using ./configure and then make because of the error described below, I continued to mess around for a bit and was able to reproduce it multiple times after some testing.

Installation on command line (bash):

- Installation invoked using python3 (all necessary dependency supposedly filled)
             $ sudo python3 setup.py install
I will attach the output below

**Expected behavior**
Installation of zenmap

**Version info (please complete the following information):**
 - OS: Debian Linux 12 (Bookworm) latest linux (stable) linux kernel - no LTS
 - Zenmap version from "zenmap 7.94SVN"

$ sudo python3 setup.py install
/usr/lib/python3/dist-packages/setuptools/dist.py:548: UserWarning: The version specified ('7.94SVN') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
warnings.warn(
running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
warnings.warn(
running build
running build_py
running build_scripts
running install_lib
running install_data
running install_egg_info
Traceback (most recent call last):
File "/home/kira/programing/zenmap_fixes/zenmap/setup.py", line 585, in <module>
setup(**setup_args)
File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 108, in setup
return distutils.core.setup(**attrs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 185, in setup
return run_commands(dist)
^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
dist.run_commands()
File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
self.run_command(cmd)
File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
super().run_command(command)
File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/home/kira/programing/zenmap_fixes/zenmap/setup.py", line 180, in run
install.run(self)
File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 72, in run
orig.install.run(self)
File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 709, in run
self.run_command(cmd_name)
File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
self.distribution.run_command(command)
File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
super().run_command(command)
File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 987, in run_command
cmd_obj.ensure_finalized()
File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
self.finalize_options()
File "/usr/lib/python3/dist-packages/setuptools/command/install_egg_info.py", line 31, in finalize_options
ei_cmd = self.get_finalized_command("egg_info")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
cmd_obj.ensure_finalized()
File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
self.finalize_options()
File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 219, in finalize_options
parsed_version = parse_version(self.egg_version)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '7.94SVN'

I am going to continue to work on bug fixing this in my free time but I just wanted to bring this to your attention in case this was unknown.

**Comment by TannerSchultz2006** [comment]
https://github.com/nmap/nmap/pull/2720
Issues is closed.
