### ISSUE TITLE
Edit the configuration to collapse

### ISSUE THREAD

**Issue by CMJNB** [nmap/nmap#2795]
**Describe the bug**
When opening profile -> Edit Selected Profile, an exception will be reported

**To Reproduce**
Open profile -> Edit Selected
```
Version: 7.94
Traceback (most recent call last):
  File "D:\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScriptInterface.py", line 261, in script_list_timer_callback
    callback(True, process)
  File "D:\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScriptInterface.py", line 270, in initial_script_list_cb
    if status and self.handle_initial_script_list_output(process):
  File "D:\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScriptInterface.py", line 301, in handle_initial_script_list_output
    for entry in get_script_entries(
  File "D:\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\ScriptMetadata.py", line 423, in get_script_entries
    metadata = ScriptMetadata(scripts_dir, nselib_dir)
  File "D:\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\ScriptMetadata.py", line 286, in __init__
    self.construct_library_arguments()
  File "D:\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\ScriptMetadata.py", line 416, in construct_library_arguments
    self.library_arguments[libname] = self.get_script_args(filepath)
  File "D:\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\ScriptMetadata.py", line 362, in get_script_args
    args = ScriptMetadata.get_script_args_from_file(f)
  File "D:\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\ScriptMetadata.py", line 370, in get_script_args_from_file
    for tag_name, tag_text in nsedoc_tags_iter(f):
  File "D:\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\ScriptMetadata.py", line 232, in nsedoc_tags_iter
    for line in f:
  File "dist/zenmap-w64/mingw64/lib/python3.10/codecs.py", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode byte 0x93 in position 5665: No mapping for the Unicode character exists in the target code page.
```

**Expected behavior**
Open normally and display in Chinese

**Version info (please complete the following information):**
 - OS：
Version Windows 11 Pro
Version 23H2
Installation date ‎2024/‎2/‎6
Operating system version 22631.3155
Experience Windows Feature Experience Pack 1000.22684.1000.0
System language: Simplified Chinese

 - Zenmap version： 7.94

 - Output of `nmap --version`:
Nmap version 7.94 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.4.4 openssl-3.0.8 nmap-libssh2-1.10.0 nmap-libz-1.2.13 nmap-libpcre-7.6 Npcap-1.75 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select

**Additional context**
Add any other context about the problem here, such as special network type.

**Comment by dmiller-nmap** [comment]
Duplicate of #2754
