### ISSUE TITLE
Zenmap crashes when file not found with error like: "UnicodeEncodeError: 'utf-8' codec can't encode characters in position 897-900: surrogates not allowed"

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#2822]
We've received many reports (often with tracebacks but very little other context) of Zenmap crashes with a UnicodeEncodeError when a file isn't found.  Here are some Tracebacks that were sent to the public Nmap development list that might help us track this down:

Traceback (most recent call last):
  File "D:\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 476, in execute_command
    command_execution.run_scan()
  File "D:\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\NmapCommand.py", line 224, in run_scan
    self.command_process = subprocess.Popen(command_list, bufsize=1,
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 971, in __init__
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 388, in start_scan_cb
    self.execute_command(command, target, profile)
  File "D:\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 503, in execute_command
    warn_dialog = HIGAlertDialog(
  File "D:\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\higwidgets\higdialogs.py", line 114, in __init__
    self.format_secondary_text(secondary_text)
  File "dist/zenmap-w64/mingw64/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 632, in format_secondary_text
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 897-900: surrogates not allowed

تم الإرسال من البريد لـ Windows
 
Version: 7.94

Traceback (most recent call last):
  File "D:\xiaodi8\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 476, in execute_command
    command_execution.run_scan()
  File "D:\xiaodi8\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\NmapCommand.py", line 224, in run_scan
    self.command_process = subprocess.Popen(command_list, bufsize=1,
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 971, in __init__
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\xiaodi8\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 388, in start_scan_cb
    self.execute_command(command, target, profile)
  File "D:\xiaodi8\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 503, in execute_command
    warn_dialog = HIGAlertDialog(
  File "D:\xiaodi8\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\higwidgets\higdialogs.py", line 114, in __init__
    self.format_secondary_text(secondary_text)
  File "dist/zenmap-w64/mingw64/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 632, in format_secondary_text
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb5' in position 792: surrogates not allowed

Version: 7.94
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 476, in execute_command
    command_execution.run_scan()
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\NmapCommand.py", line 224, in run_scan
    self.command_process = subprocess.Popen(command_list, bufsize=1,
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 971, in __init__
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 388, in start_scan_cb
    self.execute_command(command, target, profile)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 503, in execute_command
    warn_dialog = HIGAlertDialog(
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\higwidgets\higdialogs.py", line 114, in __init__
    self.format_secondary_text(secondary_text)
  File "dist/zenmap-w64/mingw64/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 632, in format_secondary_text
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 249-250: surrogates not allowed

Version: 7.94
Traceback (most recent call last):
  File "D:\basicTools\nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 476, in execute_command
    command_execution.run_scan()
  File "D:\basicTools\nmap\zenmap\lib\python3.10\site-packages\zenmapCore\NmapCommand.py", line 224, in run_scan
    self.command_process = subprocess.Popen(command_list, bufsize=1,
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 971, in __init__
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\basicTools\nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 388, in start_scan_cb
    self.execute_command(command, target, profile)
  File "D:\basicTools\nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 503, in execute_command
    warn_dialog = HIGAlertDialog(
  File "D:\basicTools\nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\higwidgets\higdialogs.py", line 114, in __init__
    self.format_secondary_text(secondary_text)
  File "dist/zenmap-w64/mingw64/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 632, in format_secondary_text
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 601-606: surrogates not allowed

Version: 7.94
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 476, in execute_command
    command_execution.run_scan()
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\NmapCommand.py", line 224, in run_scan
    self.command_process = subprocess.Popen(command_list, bufsize=1,
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 971, in __init__
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 388, in start_scan_cb
    self.execute_command(command, target, profile)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 503, in execute_command
    warn_dialog = HIGAlertDialog(
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\higwidgets\higdialogs.py", line 114, in __init__
    self.format_secondary_text(secondary_text)
  File "dist/zenmap-w64/mingw64/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 632, in format_secondary_text
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 97-102: surrogates not allowed

Version: 7.94
Traceback (most recent call last):
  File "C:\Users\jimod\Desktop\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 476, in execute_command
    command_execution.run_scan()
  File "C:\Users\jimod\Desktop\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\NmapCommand.py", line 224, in run_scan
    self.command_process = subprocess.Popen(command_list, bufsize=1,
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 971, in __init__
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\jimod\Desktop\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 388, in start_scan_cb
    self.execute_command(command, target, profile)
  File "C:\Users\jimod\Desktop\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 503, in execute_command
    warn_dialog = HIGAlertDialog(
  File "C:\Users\jimod\Desktop\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\higwidgets\higdialogs.py", line 114, in __init__
    self.format_secondary_text(secondary_text)
  File "dist/zenmap-w64/mingw64/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 632, in format_secondary_text
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcd0' in position 143: surrogates not allowed

Version: 7.94
Traceback (most recent call last):
  File "D:\nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 476, in execute_command
    command_execution.run_scan()
  File "D:\nmap\zenmap\lib\python3.10\site-packages\zenmapCore\NmapCommand.py", line 224, in run_scan
    self.command_process = subprocess.Popen(command_list, bufsize=1,
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 971, in __init__
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 388, in start_scan_cb
    self.execute_command(command, target, profile)
  File "D:\nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 503, in execute_command
    warn_dialog = HIGAlertDialog(
  File "D:\nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\higwidgets\higdialogs.py", line 114, in __init__
    self.format_secondary_text(secondary_text)
  File "dist/zenmap-w64/mingw64/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 632, in format_secondary_text
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 160-161: surrogates not allowed

Version: 7.94
Traceback (most recent call last):
  File "D:\a\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 476, in execute_command
    command_execution.run_scan()
  File "D:\a\Nmap\zenmap\lib\python3.10\site-packages\zenmapCore\NmapCommand.py", line 224, in run_scan
    self.command_process = subprocess.Popen(command_list, bufsize=1,
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 971, in __init__
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 388, in start_scan_cb
    self.execute_command(command, target, profile)
  File "D:\a\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 503, in execute_command
    warn_dialog = HIGAlertDialog(
  File "D:\a\Nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\higwidgets\higdialogs.py", line 114, in __init__
    self.format_secondary_text(secondary_text)
  File "dist/zenmap-w64/mingw64/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 632, in format_secondary_text
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 611-614: surrogates not allowed

从 Windows 版[邮件](https://go.microsoft.com/fwlink/?LinkId=550986)发送

Version: 7.94

Traceback (most recent call last):
  File "D:\tools\1\nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 476, in execute_command
    command_execution.run_scan()
  File "D:\tools\1\nmap\zenmap\lib\python3.10\site-packages\zenmapCore\NmapCommand.py", line 224, in run_scan
    self.command_process = subprocess.Popen(command_list, bufsize=1,
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 971, in __init__
  File "dist/zenmap-w64/mingw64/lib/python3.10/subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred: 

Traceback (most recent call last):
  File "D:\tools\1\nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 388, in start_scan_cb
    self.execute_command(command, target, profile)
  File "D:\tools\1\nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\ScanInterface.py", line 503, in execute_command
    warn_dialog = HIGAlertDialog(
  File "D:\tools\1\nmap\zenmap\lib\python3.10\site-packages\zenmapGUI\higwidgets\higdialogs.py", line 114, in __init__
    self.format_secondary_text(secondary_text)
  File "dist/zenmap-w64/mingw64/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 632, in format_secondary_text
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 1010-1011: surrogates not allowed

**Comment by dmiller-nmap** [comment]
This is most likely due to the fact that we include the value of the `PATH` environment variable in this error, and the filesystem paths are either not being decoded correctly or they contain unpaired surrogates.  Prior to Python 3.6 this wasn't a problem because Python used the ANSI versions of the Windows API functions. For more, see [PEP-529](https://peps.python.org/pep-0529/). A workaround may be to set the `PYTHONLEGACYWINDOWSFSENCODING` environment variable when running Zenmap.

**Comment by dmiller-nmap** [comment]
It looks like the most likely case is surrogate pairs in the PATH variable. CPython appears to just copy the bytes directly from the Windows API call into a unicode string, which works until you go to encode it. I think at that point we need to use a different error handler such as `surrogatepass`, `surrogateescape`, or `replace`, possibly doing a encode/decode cycle to make the string safe to pass to `format_secondary_text()`. It would be most helpful if someone could reproduce this with Zenmap 7.95 and provide a traceback.

**Comment by fyodor** [comment]
We think this may be fixed as we haven't been seeing reports with Nmap 7.95 or later.  If anyone is still seeing it with Nmap 7.98, please comment here.

**Comment by fyodor** [comment]
We haven't heard any more reports after this, so the issue is probably no longer present in recent releases and I'm marking it closed.  If anyone does see it, please comment here and we'll re-open.
