### ISSUE TITLE
Version 7.95. Crash after starting nmap ‐sV ‐‐version‐all 

### ISSUE THREAD

**Issue by Modrenman** [nmap/nmap#2823]
**Describe the bug**
 Crash after starting nmap ‐sV ‐‐version‐all 
Here are the traceback by the crash message box:

Version: 7.95
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanInterface.py", line 370, in start_scan_cb
    self.toolbar.add_new_target(target)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanToolbar.py", line 150, in add_new_target
    self.target_entry.add_new_target(target)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\TargetCombo.py", line 86, in add_new_target
    target_list.add_target(target)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\TargetList.py", line 99, in add_target
    self.save()
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\TargetList.py", line 91, in save
    target_file.write(";".join(self.temp_list))
  File "../lib/python3.11/encodings/cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u2010' in position 0: character maps to <undefined>

**To Reproduce**
1. Start Zenmap 7.95
2. input command nmap ‐sV ‐‐version‐all IP (IP is needed to scan IP-address)
3.  Crash

**Expected behavior**
Expected to happen correct command execution and no program crash

**Version info (please complete the following information):**
 - OS: Windows 11
 - Zenmap version 7.95
 - Output of `nmap --version`: 
Nmap version 7.95 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.4.6 openssl-3.0.13 nmap-libssh2-1.11.0 nmap-libz-1.3.1 nmap-libpcre2-10.43 Npcap-1.79 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select

**Comment by Modrenman** [comment]
Well, after aggressive version scanning (nmap -sV --version-intensity 5), Zenmap stopped crashing from this particular command, I’m not sure what is causing the bug and what caused the fix.
