### ISSUE TITLE
zenmap error report

### ISSUE THREAD

**Issue by sjkufo3261** [nmap/nmap#2832]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**
when i select the menu "profile"--"edit selected profile", get the following error:
Version: 7.95
Traceback (most recent call last):
  File "D:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScriptInterface.py", line 262, in script_list_timer_callback
    callback(True, process)
  File "D:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScriptInterface.py", line 271, in initial_script_list_cb
    if status and self.handle_initial_script_list_output(process):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScriptInterface.py", line 302, in handle_initial_script_list_output
    for entry in get_script_entries(
                 ^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\ScriptMetadata.py", line 424, in get_script_entries
    metadata = ScriptMetadata(scripts_dir, nselib_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\ScriptMetadata.py", line 287, in __init__
    self.construct_library_arguments()
  File "D:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\ScriptMetadata.py", line 417, in construct_library_arguments
    self.library_arguments[libname] = self.get_script_args(filepath)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\ScriptMetadata.py", line 363, in get_script_args
    args = ScriptMetadata.get_script_args_from_file(f)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\ScriptMetadata.py", line 371, in get_script_args_from_file
    for tag_name, tag_text in nsedoc_tags_iter(f):
  File "D:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\ScriptMetadata.py", line 233, in nsedoc_tags_iter
    for line in f:
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode byte 0x93 in position 5665: No mapping for the Unicode character exists in the target code page.

**To Reproduce**
Steps to reproduce the behavior, including command-line options.

**Expected behavior**

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]
 - Output of `nmap --version`:
 - Output of `nmap --iflist`

**Additional context**
Add any other context about the problem here, such as special network type.

**Comment by dmiller-nmap** [comment]
Duplicate of #2754
