### ISSUE TITLE
Zenmap Crash Report

### ISSUE THREAD

**Issue by zurynnn** [nmap/nmap#2840]
Version: 7.95
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\DiffCompare.py", line 380, in check_ndiff_process
    stderr = self.ndiff_process.stderr.read()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'read'
![Screenshot 2024-05-14 220554](https://github.com/nmap/nmap/assets/169817251/5edd6edd-eed4-420f-b111-acfd775acbfe)

**Comment by yangchangguk** [comment]
Version: 7.95
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\App.py", line 286, in run
    window = new_window()
             ^^^^^^^^^^^^
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\App.py", line 129, in new_window
    from zenmapGUI.MainWindow import ScanWindow
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 92, in <module>
    from zenmapCore.RecentScans import recent_scans
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\RecentScans.py", line 110, in <module>
    recent_scans = RecentScans()
                   ^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\RecentScans.py", line 81, in __init__
    t for t in recent_file.read().split(";")
               ^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

**Comment by dmiller-nmap** [comment]
Duplicate of #2854
