### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by shifosss** [nmap/nmap#2845]
**Describe the bug**
Whenever I open the Profile-New Profile or Command, it crashed. I have repeated it for several times and it appears everytime.

**To Reproduce**
Open Zenmap, and open Profile - New Profile or Command.

**Expected behavior**
I should be able to edit a new profile.

**Version info (please complete the following information):**
 - OS: Windows 11 (22621.3593)
 - Zenmap version from `Help` -> `About`: 7.95
 - Output of `nmap --version`: (as follows)
Nmap version 7.95 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.4.6 openssl-3.0.13 nmap-libssh2-1.11.0 nmap-libz-1.3.1 nmap-libpcre2-10.43 Npcap-1.79 nmap-libdnet-1.12 ipv6

**Additional context**

Version: 7.95
Traceback (most recent call last):
  File "D:\Programs\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScriptInterface.py", line 262, in script_list_timer_callback
    callback(True, process)
  File "D:\Programs\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScriptInterface.py", line 271, in initial_script_list_cb
    if status and self.handle_initial_script_list_output(process):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScriptInterface.py", line 302, in handle_initial_script_list_output
    for entry in get_script_entries(
                 ^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\ScriptMetadata.py", line 424, in get_script_entries
    metadata = ScriptMetadata(scripts_dir, nselib_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\ScriptMetadata.py", line 287, in __init__
    self.construct_library_arguments()
  File "D:\Programs\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\ScriptMetadata.py", line 417, in construct_library_arguments
    self.library_arguments[libname] = self.get_script_args(filepath)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\ScriptMetadata.py", line 363, in get_script_args
    args = ScriptMetadata.get_script_args_from_file(f)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\ScriptMetadata.py", line 371, in get_script_args_from_file
    for tag_name, tag_text in nsedoc_tags_iter(f):
  File "D:\Programs\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\ScriptMetadata.py", line 233, in nsedoc_tags_iter
    for line in f:
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode byte 0x93 in position 5665: No mapping for the Unicode character exists in the target code page.

**Comment by dmiller-nmap** [comment]
Duplicate of #2754
