### ISSUE TITLE
Unexpected crash of Zenmap 7.95

### ISSUE THREAD

**Issue by mikaxiwa** [nmap/nmap#2860]
Version: 7.95
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\App.py", line 286, in run
    window = new_window()
             ^^^^^^^^^^^^
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\App.py", line 129, in new_window
    from zenmapGUI.MainWindow import ScanWindow
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 92, in <module>
    from zenmapCore.RecentScans import recent_scans
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\RecentScans.py", line 110, in <module>
    recent_scans = RecentScans()
                   ^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\RecentScans.py", line 81, in __init__
    t for t in recent_file.read().split(";")
               ^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

**Comment by TAKAHASHI7** [comment]
请问解决了吗？

**Comment by mikaxiwa** [comment]
未解决

**Comment by lw7898** [comment]
修改C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\RecentScans.py 中的：
recent_file = open(self.recent_scans_file, "r")
为：
recent_file = open(self.recent_scans_file, "r", encoding='UTF-8')
可以解决问题
