### ISSUE TITLE
nmap的错误报告

### ISSUE THREAD

**Issue by IN0420** [nmap/nmap#2876]
Version: 7.95
Traceback (most recent call last):
  File "C:\Users\lisa\Desktop\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanInterface.py", line 370, in start_scan_cb
    self.toolbar.add_new_target(target)
  File "C:\Users\lisa\Desktop\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanToolbar.py", line 150, in add_new_target
    self.target_entry.add_new_target(target)
  File "C:\Users\lisa\Desktop\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\TargetCombo.py", line 86, in add_new_target
    target_list.add_target(target)
  File "C:\Users\lisa\Desktop\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\TargetList.py", line 99, in add_target
    self.save()
  File "C:\Users\lisa\Desktop\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\TargetList.py", line 91, in save
    target_file.write(";".join(self.temp_list))
  File "../lib/python3.11/encodings/mbcs.py", line 25, in encode
UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character

**Comment by dmiller-nmap** [comment]
Thanks for this report. We believe this is fixed in c840e236cb43cfa57d2542a3fc3688807cc90387, which will be released in the next version of Nmap.
