### ISSUE TITLE
Zenmap Crashes When Saving Scan to XML File Format

### ISSUE THREAD

**Issue by dbwadamz** [nmap/nmap#2880]
**Describe the bug**
Attempted to save a scan as an XML document.

**To Reproduce**
Run a scan.  When scan completes, click Scan on the menu bar and then click Save Scan.  Choose XML as the type, name the file, then click Save.

**Expected behavior**
File should save in the XML file format. 

**Version info (please complete the following information):**
 - OS: Windows 11 Pro 23H2 Build 22631.3737
 - Zenmap version 7.95
 - Output of `nmap --version`:
Nmap version 7.95 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.4.6 openssl-3.0.13 nmap-libssh2-1.11.0 nmap-libz-1.3.1 nmap-libpcre2-10.43 Npcap-1.79 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select

**Additional context**
The file appears to save, but when attempting to Open Scan, the 'Error loading file' dialog appears with the following error: "filename.xml:4387:57303: unclosed token"

Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 629, in _save_scan_results_cb
    self._save(self.scan_interface, filename, selected, format)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 711, in _save
    scan_interface.inventory.save_to_file(
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NetworkInventory.py", line 291, in save_to_file
    self.get_scans()[index].write_xml(f)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1020, in write_xml
    self._write_hosts(writer)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1101, in _write_hosts
    writer.startElement("address",
  File "../lib/python3.11/xml/sax/saxutils.py", line 170, in startElement
  File "../lib/python3.11/encodings/cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 37-38: character maps to <undefined>

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. We believe this is fixed in c840e236cb43cfa57d2542a3fc3688807cc90387, which will be released in the next version of Nmap.
