### ISSUE TITLE
zenmap crashes when starting...

### ISSUE THREAD

**Issue by lw7898** [nmap/nmap#2903]
Version: 7.95
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\App.py", line 286, in run
    window = new_window()
             ^^^^^^^^^^^^
  File "C:\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\App.py", line 129, in new_window
    from zenmapGUI.MainWindow import ScanWindow
  File "C:\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 92, in <module>
    from zenmapCore.RecentScans import recent_scans
  File "C:\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\RecentScans.py", line 110, in <module>
    recent_scans = RecentScans()
                   ^^^^^^^^^^^^^
  File "C:\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\RecentScans.py", line 81, in __init__
    t for t in recent_file.read().split(";")
               ^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

**Comment by attacker2001** [comment]
D:\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\RecentScans.py

from `recent_file = open(self.recent_scans_file, "r")` 
to `recent_file = open(self.recent_scans_file, "r", encoding='utf8')`
![image](https://github.com/user-attachments/assets/49351bed-e0b4-46c2-9e6c-e7f83f649db5)

```
            # Recovering saved targets
            recent_file = open(self.recent_scans_file, "r", encoding='utf8')
            self.temp_list = [
                    t for t in recent_file.read().split(";")
                    if t != "" and t != "\n"]
            recent_file.close()
        else:
            self.using_file = False

```

**Comment by dmiller-nmap** [comment]
Fixed in c840e236cb43cfa57d2542a3fc3688807cc90387
