### ISSUE TITLE
Version: 7.95 Traceback (most recent call last):   File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\DiffCompare.py", line 380, in check_ndiff_process     stderr = self.ndiff_process.stderr.read()              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'read'

### ISSUE THREAD

**Issue by netthan01** [nmap/nmap#2905]
Version: 7.95
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\DiffCompare.py", line 380, in check_ndiff_process
    stderr = self.ndiff_process.stderr.read()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'read'

**Comment by dmiller-nmap** [comment]
Duplicate of #2854
