### ISSUE TITLE
Cannot save to downloads folder that are in OneDrive

### ISSUE THREAD

**Issue by WolfChunin** [nmap/nmap#2921]
**Describe the bug**
The scan cannot be saved into the folder inside Downloads which are currently in the OneDrive

**To Reproduce**
Steps to reproduce the behavior, including window titles and command-line options.
press Ctrl + s
navigate to the Downloads folder in OneDrive
click save

**Expected behavior**

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]
 - Zenmap version from `Help` -> `About`
 - Output of `nmap --version`:
Windows 11 Enterprise 23H2
Zenmap 7.95
**Additional context**
Add any other context about the problem here, such as special network type.
Version: 7.95
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 629, in _save_scan_results_cb
    self._save(self.scan_interface, filename, selected, format)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 711, in _save
    scan_interface.inventory.save_to_file(
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NetworkInventory.py", line 291, in save_to_file
    self.get_scans()[index].write_xml(f)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1020, in write_xml
    self._write_hosts(writer)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1101, in _write_hosts
    writer.startElement("address",
  File "../lib/python3.11/xml/sax/saxutils.py", line 170, in startElement
  File "../lib/python3.11/encodings/cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 37-38: character maps to <undefined>

More error code when using zenmap with privileges
Version: 7.95
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 629, in _save_scan_results_cb
    self._save(self.scan_interface, filename, selected, format)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 711, in _save
    scan_interface.inventory.save_to_file(
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NetworkInventory.py", line 291, in save_to_file
    self.get_scans()[index].write_xml(f)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1020, in write_xml
    self._write_hosts(writer)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1101, in _write_hosts
    writer.startElement("address",
  File "../lib/python3.11/xml/sax/saxutils.py", line 170, in startElement
  File "../lib/python3.11/encodings/cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 37-38: character maps to <undefined>

**Comment by dmiller-nmap** [comment]
Duplicate of #2880
