### ISSUE TITLE
Ndiff 7.95 returns TypeError: '<' not supported between instances of 'ScriptResult' and 'ScriptResult'

### ISSUE THREAD

**Issue by drwetter** [nmap/nmap#2930]
**Describe the current behavior**
A client of mine wanted me to scan networks from two different scan hosts A and B.

I tried to compare the scans via ndiff and it returns an error (first nmap 7.95 from nmap.org):

```
prompt> ndiff /tmp/dns-records-a.txt_-A.20240903-0452.xml ./dns-records-a.txt_-A.20240905-1315.xml                                                        
Traceback (most recent call last):
File "/usr/bin/ndiff", line 84, in <module>
sys.exit(ndiff.main())
File "/usr/lib/python3.11/site-packages/ndiff.py", line 1505, in main
scan_a.load_from_file(filename_a)
File "/usr/lib/python3.11/site-packages/ndiff.py", line 72, in load_from_file
self.load(f)
File "/usr/lib/python3.11/site-packages/ndiff.py", line 67, in load
parser.parse(f)
File "/usr/lib/python3.10/xml/sax/expatreader.py", line 111, in parse
xmlreader.IncrementalParser.parse(self, source)
File "/usr/lib/python3.10/xml/sax/xmlreader.py", line 125, in parse
self.feed(buffer)
File "/usr/lib/python3.10/xml/sax/expatreader.py", line 217, in feed
self._parser.Parse(data, isFinal)
File "../Modules/pyexpat.c", line 468, in EndElement
File "/usr/lib/python3.10/xml/sax/expatreader.py", line 336, in end_element
self._cont_handler.endElement(name)
File "/usr/lib/python3.11/site-packages/ndiff.py", line 1239, in endElement
handler(name)
File "/usr/lib/python3.11/site-packages/ndiff.py", line 1420, in _end_port
self.current_port.script_results.sort()
TypeError: '<' not supported between instances of 'ScriptResult' and 'ScriptResult'
prompt>
```

The scans were both started by helper scripts by me, so they were started with the same parameters . And just to make sure I used vim in diff mode for comparison ✅

**Expected behavior**
A fine output which lists the difference for ports which can be accessed / not accessed from A and B.

**Comment by junedic** [comment]
Hello,

so this appears to occur due to the `ScriptResult` class in ndiff.py not specifying a `__lt__` method by which the precedence of its instances could be compared for sorting. The bug itself would only be hit when exporting more than one script result (i.e. running more than one successful script presumably).

#2932 should be sufficient to fix this issue.

**Comment by junedic** [comment]
Looks like someone forgot to wrap the field in a len function, should be an easy fix. After a quick skim-through there appear to be some other instances of comparison that should be checked as well. I will post a commit later in the day.

**Comment by junedic** [comment]
@drwetter You can try #2933. Other similar logic looks sane implementation wise. I added some style changes to another class's comparison implementation and did some tests that produced equal results.

**Comment by MartinRoDEsoft** [comment]
@junedic Your fix in ndiff.py fixes the issue for me.
