### ISSUE TITLE
Application crashed when trying to save a quick scan

### ISSUE THREAD

**Issue by sunnyleung** [nmap/nmap#2935]
**Describe the bug**
Application crash when attempting to save

**To Reproduce**
Steps to reproduce the behavior, including window titles and command-line options.

Ran quick scan. Scan-->Save Scan

**Expected behavior**
Ability to save scan to examine later. 

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]
 - Zenmap version from `Help` -> `About`
 - Output of `nmap --version`:

7.95

**Additional context**

Crash Report

Add any other context about the problem here, such as special network type.
Version: 7.95
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 629, in _save_scan_results_cb
    self._save(self.scan_interface, filename, selected, format)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 711, in _save
    scan_interface.inventory.save_to_file(
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NetworkInventory.py", line 291, in save_to_file
    self.get_scans()[index].write_xml(f)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1020, in write_xml
    self._write_hosts(writer)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1101, in _write_hosts
    writer.startElement("address",
  File "../lib/python3.11/xml/sax/saxutils.py", line 170, in startElement
  File "../lib/python3.11/encodings/cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 37-38: character maps to <undefined>

**Comment by FileNotFound7** [comment]
I'm experiencing this issue when trying to save a ping scan. This also appears to be the same issue to #2880, since the traceback is the same, and I had the exact same too. 
`nmap --version` outputs the following:
```
Nmap version 7.95 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.4.6 openssl-3.0.13 nmap-libssh2-1.11.0 nmap-libz-1.3.1 nmap-libpcre2-10.43 Npcap-1.80 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select
```

**Comment by dmiller-nmap** [comment]
Duplicate of #2880
