### ISSUE TITLE
Nmap segfault in libdnet

### ISSUE THREAD

**Issue by whistlerwzc** [nmap/nmap#2937]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the current behavior**
I have upgraded Nmap to v7.95 and still encountered a segfault, after debugging, I found the reason in _intf_get_aliases which may cause stackoverflow during inet6 address processing, heres the backtrace:
(gdb) bt
#0  __stack_chk_fail () at src/env/__stack_chk_fail.c:26
#1  0x00005555557a5021 in intf_loop (intf=0x7ffff77d91d0, callback=0x555555786337 <collect_dnet_interfaces(intf_entry const*, void*)>,
    arg=0x7fffffffce60) at intf.c:951
#2  0x0000555555786aa8 in getinterfaces_dnet (howmany=0x555555a424f0 <getinterfaces(int*, char*, unsigned long)::numifaces>, errstr=0x0,
    errstrlen=0) at netutil.cc:1381
#3  0x0000555555786b58 in getinterfaces (howmany=0x7fffffffcee8, errstr=0x0, errstrlen=0) at netutil.cc:1403
#4  0x0000555555786e66 in getInterfaceByName (iname=0x7fffffffd010 "mgt0", af=2) at netutil.cc:1466
#5  0x0000555555787814 in collect_dnet_routes (entry=0x7fffffffd010, arg=0x7fffffffd4e0) at netutil.cc:1650
#6  0x00005555557a5b19 in route_loop (r=0x7ffff7ffe8b0, callback=0x5555557876ab <collect_dnet_routes(route_entry const*, void*)>,
    arg=0x7fffffffd4e0) at route-linux.c:257
#7  0x0000555555787939 in getsysroutes_dnet (howmany=0x7fffffffd580, errstr=0x7fffffffd5d0 "", errstrlen=256) at netutil.cc:1674
#8  0x0000555555787a74 in getsysroutes (howmany=0x7fffffffd580, errstr=0x7fffffffd5d0 "", errstrlen=256) at netutil.cc:1711
#9  0x000055555578e645 in route_dst_generic (dst=0x7fffffffdad0, rnfo=0x7fffffffd8a0, device=0x555555a1f400 <o+32> "", spoofss=0x0)
    at netutil.cc:3346
#10 0x000055555578f307 in route_dst (dst=0x7fffffffdad0, rnfo=0x7fffffffd8a0, device=0x555555a1f400 <o+32> "", spoofss=0x0) at netutil.cc:3452
#11 0x00005555556c7f63 in nmap_route_dst (dst=0x7fffffffdad0, rnfo=0x7fffffffd8a0) at tcpip.cc:1727
#12 0x00005555556c11d6 in setup_target (hs=0x7fffffffddc0, ss=0x7fffffffdad0, sslen=16, pingtype=122) at targets.cc:375
#13 0x00005555556c176c in next_target (hs=0x7fffffffddc0, exclude_group=0x7ffff7f57c00, ports=0x555555a1f240 <ports>, pingtype=122)
    at targets.cc:471
#14 0x00005555556c1857 in refresh_hostbatch (hs=0x7fffffffddc0, exclude_group=0x7ffff7f57c00, ports=0x555555a1f240 <ports>, pingtype=122)
    at targets.cc:493
#15 0x00005555556c1e85 in nexthost (hs=0x7fffffffddc0, exclude_group=0x7ffff7f57c00, ports=0x555555a1f240 <ports>, pingtype=122)
    at targets.cc:579
#16 0x000055555564736d in nmap_main (argc=2, argv=0x7fffffffed68) at nmap.cc:2104
#17 0x00005555556f4819 in main (argc=2, argv=0x7fffffffed68) at main.cc:170

The newest libdnet has already fixed it by change:
- while ( ap < lap && 
+ while ( ap +1 < lap
I would like to give an upgrade suggestion on it.

**Expected behavior**
Nmap will not crash

**Comment by dmiller-nmap** [comment]
Nmap 7.96 has rebased our changes on upstream libdnet 1.18, including the fix for this issue.
