### ISSUE TITLE
crash report from Nmap v7.95

### ISSUE THREAD

**Issue by beedub1234** [nmap/nmap#2951]
OS: Windows 11 Enterprise, Version 23H2 Build 22631.4317
Nmap version: 7.95
Npcap version: 1.80 (also failed with 1.79)
Command to produce crash: nmap –p– 137.168.170.25 (IP address of my own computer)

Output of "nmap --version":
Nmap version 7.95 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.4.6 openssl-3.0.13 nmap-libssh2-1.11.0 nmap-libz-1.3.1 nmap-libpcre2-10.43 Npcap-1.80 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select

Output of "nmap --iflist":
Starting Nmap 7.95 ( https://nmap.org ) at 2024-10-17 13:50 Pacific Daylight Time
************************INTERFACES************************
DEV  (SHORT) IP/MASK                      TYPE     UP   MTU  MAC
eth0 (eth0)  fe80::64ae:9f2e:d0d9:e27c/64 ethernet up   1500 00:2B:67:BB:96:C9
eth0 (eth0)  137.168.170.25/24            ethernet up   1500 00:2B:67:BB:96:C9
eth1 (eth1)  fe80::233a:b058:d574:a575/64 ethernet down 1500 F8:AC:65:E5:C3:2F
eth1 (eth1)  169.254.192.12/16            ethernet down 1500 F8:AC:65:E5:C3:2F
eth2 (eth2)  fe80::c0d4:50a1:577d:88bf/64 ethernet down 1500 FA:AC:65:E5:C3:2E
eth2 (eth2)  169.254.203.115/16           ethernet down 1500 FA:AC:65:E5:C3:2E
eth3 (eth3)  fe80::c5b3:b95b:84c2:4e4a/64 ethernet up   1500 00:50:56:C0:00:01
eth3 (eth3)  192.168.0.247/24             ethernet up   1500 00:50:56:C0:00:01
eth4 (eth4)  fe80::c6f0:648b:befd:366d/64 ethernet up   1500 00:50:56:C0:00:08
eth4 (eth4)  192.168.239.1/24             ethernet up   1500 00:50:56:C0:00:08
eth5 (eth5)  fe80::d2c6:adfa:c6af:2e64/64 ethernet down 1500 F8:AC:65:E5:C3:2E
eth5 (eth5)  169.254.68.64/16             ethernet down 1500 F8:AC:65:E5:C3:2E
eth6 (eth6)  fe80::a393:731b:896f:ca9a/64 ethernet down 1500 F8:AC:65:E5:C3:32
eth6 (eth6)  169.254.42.242/16            ethernet down 1500 F8:AC:65:E5:C3:32
lo0  (lo0)   ::1/128                      loopback up   -1
lo0  (lo0)   127.0.0.1/8                  loopback up   -1
eth7 (eth7)  fe80::619:89ce:f3a1:5496/64  ethernet up   1500 00:15:5D:86:50:01
eth7 (eth7)  172.20.128.1/20              ethernet up   1500 00:15:5D:86:50:01

DEV    WINDEVICE
eth0   \Device\NPF_{50965BD4-D778-4769-A8B2-53A47A3336BA}
eth0   \Device\NPF_{50965BD4-D778-4769-A8B2-53A47A3336BA}
eth1   \Device\NPF_{FBC2B235-AA0E-48CF-A580-F9B07F0B7D6E}
eth1   \Device\NPF_{FBC2B235-AA0E-48CF-A580-F9B07F0B7D6E}
eth2   \Device\NPF_{54E5B617-B69B-4C75-BA1E-D4224FACFBFD}
eth2   \Device\NPF_{54E5B617-B69B-4C75-BA1E-D4224FACFBFD}
eth3   \Device\NPF_{5C125AD9-9846-4627-8B70-71A8FEC5C718}
eth3   \Device\NPF_{5C125AD9-9846-4627-8B70-71A8FEC5C718}
eth4   \Device\NPF_{CAF54B61-643F-4DA4-9410-233C9876A988}
eth4   \Device\NPF_{CAF54B61-643F-4DA4-9410-233C9876A988}
eth5   \Device\NPF_{DAA6A685-40AE-4DD7-9389-F479F89BDAAB}
eth5   \Device\NPF_{DAA6A685-40AE-4DD7-9389-F479F89BDAAB}
eth6   \Device\NPF_{BEE546D0-EA7D-441C-9FB0-F13AD1C0565E}
eth6   \Device\NPF_{BEE546D0-EA7D-441C-9FB0-F13AD1C0565E}
lo0    \Device\NPF_Loopback
lo0    \Device\NPF_Loopback
eth7   \Device\NPF_{B28C7DA6-36C8-4D21-95C0-B1C4AD127679}
eth7   \Device\NPF_{B28C7DA6-36C8-4D21-95C0-B1C4AD127679}
<none> \Device\NPF_{7A2D9531-E817-497A-8136-09D27987B9DE}
<none> \Device\NPF_{F98F0DBD-4E62-47E4-BFD5-4BE2BC599309}
<none> \Device\NPF_{115ED612-EC8F-4C54-8E46-78EC88CF83F5}

**************************ROUTES**************************
DST/MASK                      DEV  METRIC GATEWAY
255.255.255.255/32            eth0 281
255.255.255.255/32            eth2 281
137.168.170.255/32            eth0 281
255.255.255.255/32            eth1 281
137.168.170.25/32             eth0 281
192.168.239.255/32            eth4 291
192.168.239.1/32              eth4 291
255.255.255.255/32            eth3 291
255.255.255.255/32            eth4 291
192.168.0.247/32              eth3 291
192.168.0.255/32              eth3 291
169.254.68.64/32              eth5 296
255.255.255.255/32            eth5 296
169.254.255.255/32            eth5 296
255.255.255.255/32            eth6 321
127.0.0.1/32                  lo0  331
255.255.255.255/32            lo0  331
127.255.255.255/32            lo0  331
172.20.128.1/32               eth7 5256
172.20.143.255/32             eth7 5256
255.255.255.255/32            eth7 5256
137.168.170.0/24              eth0 281
192.168.239.0/24              eth4 291
192.168.0.0/24                eth3 291
172.20.128.0/20               eth7 5256
169.254.0.0/16                eth5 296
127.0.0.0/8                   lo0  331
224.0.0.0/4                   eth1 281
224.0.0.0/4                   eth2 281
224.0.0.0/4                   eth0 281
224.0.0.0/4                   eth3 291
224.0.0.0/4                   eth4 291
224.0.0.0/4                   eth5 296
224.0.0.0/4                   eth6 321
224.0.0.0/4                   lo0  331
224.0.0.0/4                   eth7 5256
0.0.0.0/0                     eth0 25     137.168.170.253
0.0.0.0/0                     eth5 40     137.168.134.253
fe80::c0d4:50a1:577d:88bf/128 eth2 281
fe80::64ae:9f2e:d0d9:e27c/128 eth0 281
fe80::233a:b058:d574:a575/128 eth1 281
fe80::c6f0:648b:befd:366d/128 eth4 291
fe80::c5b3:b95b:84c2:4e4a/128 eth3 291
fe80::d2c6:adfa:c6af:2e64/128 eth5 296
fe80::a393:731b:896f:ca9a/128 eth6 321
::1/128                       lo0  331
fe80::619:89ce:f3a1:5496/128  eth7 5256
fe80::/64                     eth2 281
fe80::/64                     eth1 281
fe80::/64                     eth0 281
fe80::/64                     eth3 291
fe80::/64                     eth4 291
fe80::/64                     eth5 296
fe80::/64                     eth6 321
fe80::/64                     eth7 5256
ff00::/8                      eth2 281
ff00::/8                      eth0 281
ff00::/8                      eth1 281
ff00::/8                      eth3 291
ff00::/8                      eth4 291
ff00::/8                      eth5 296
ff00::/8                      eth6 321
ff00::/8                      lo0  331
ff00::/8                      eth7 5256

Stack trace as follows.
Version: 7.95
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanInterface.py", line 370, in start_scan_cb
    self.toolbar.add_new_target(target)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanToolbar.py", line 150, in add_new_target
    self.target_entry.add_new_target(target)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\TargetCombo.py", line 86, in add_new_target
    target_list.add_target(target)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\TargetList.py", line 99, in add_target
    self.save()
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\TargetList.py", line 91, in save
    target_file.write(";".join(self.temp_list))
  File "../lib/python3.11/encodings/mbcs.py", line 25, in encode
UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character

**Comment by dmiller-nmap** [comment]
Duplicate of #2876
