### ISSUE TITLE
Crash Report(Version: 7.95)

### ISSUE THREAD

**Issue by PatrickSong34** [nmap/nmap#2968]
**Version info (please complete the following information):**
 - OS: Windows 11
 - Zenmap version from `Help` -> `About` : 7.95
 - Output of `nmap --version`:

**Additional context**
Add any other context about the problem here, such as special network type.

Version: 7.95
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanInterface.py", line 539, in verify_execution
    self.scan_result.refresh_nmap_output()
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanInterface.py", line 909, in refresh_nmap_output
    self.scan_result_notebook.nmap_output.nmap_output.refresh_output()
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\NmapOutputViewer.py", line 288, in refresh_output
    new_output = self.command_execution.stdout_file.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../lib/python3.11/tempfile.py", line 500, in func_wrapper
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

**Comment by dmiller-nmap** [comment]
We believe this is fixed in 49c25e6431579199248f51feb17c12771e5a0be4 and will be resolved in the next Nmap release.

**Comment by Twanaki** [comment]
Hi,
I still get the same error with 7.96, using Windows in French.

The error :
Version: 7.96
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.12\site-packages\zenmapGUI\ScanInterface.py", line 539, in verify_execution
    self.scan_result.refresh_nmap_output()
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.12\site-packages\zenmapGUI\ScanInterface.py", line 909, in refresh_nmap_output
    self.scan_result_notebook.nmap_output.nmap_output.refresh_output()
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.12\site-packages\zenmapGUI\NmapOutputViewer.py", line 290, in refresh_output
    new_output = self.command_execution.stdout_file.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../lib/python3.12/tempfile.py", line 499, in func_wrapper
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 82: invalid start byte

Any help ? Thanks !

**Comment by 3792274New** [comment]
Version: 7.96
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.12\site-packages\zenmapGUI\ScanInterface.py", line 539, in verify_execution
    self.scan_result.refresh_nmap_output()
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.12\site-packages\zenmapGUI\ScanInterface.py", line 909, in refresh_nmap_output
    self.scan_result_notebook.nmap_output.nmap_output.refresh_output()
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.12\site-packages\zenmapGUI\NmapOutputViewer.py", line 290, in refresh_output
    new_output = self.command_execution.stdout_file.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../lib/python3.12/tempfile.py", line 499, in func_wrapper
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 60: invalid continuation byte
