### ISSUE TITLE
when scan the internal IP range, then have this crash report coming.

### ISSUE THREAD

**Issue by mikemui** [nmap/nmap#2974]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**

**To Reproduce**
nmap -T4 -A -v -Pn 192.168.109.5-254

**Expected behavior**
Intense scan, no ping

**Version info (please complete the following information):**
 - OS: Windows 11 24H2 26100.2454
 - Output of `nmap --version`: 
Nmap version 7.95 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.4.6 openssl-3.0.13 nmap-libssh2-1.11.0 nmap-libz-1.3.1 nmap-libpcre2-10.43 Npcap-1.79 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select
 - Output of `nmap --iflist`

**Additional context**
Version: 7.95
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanInterface.py", line 539, in verify_execution
    self.scan_result.refresh_nmap_output()
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanInterface.py", line 909, in refresh_nmap_output
    self.scan_result_notebook.nmap_output.nmap_output.refresh_output()
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\NmapOutputViewer.py", line 288, in refresh_output
    new_output = self.command_execution.stdout_file.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../lib/python3.11/tempfile.py", line 500, in func_wrapper
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

**Comment by dmiller-nmap** [comment]
Duplicate of #2968
