### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by AgrisolutionsHamilton** [nmap/nmap#2976]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**
When attempting to save a Scan that has just completed.  The Zenmap software crashes.

**To Reproduce**
Run scan again and Save, it has crashed twice.

**Expected behavior**
The expected behaviour is to save the scan.

**Version info (please complete the following information):**
 - OS: Windows 11 version 24H2 OS Build 26100.2454)
 - Output of `nmap --version`: Zenmap 7.95
 - Output of `nmap --iflist`

**Additional context**
Version: 7.95
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 629, in _save_scan_results_cb
    self._save(self.scan_interface, filename, selected, format)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 711, in _save
    scan_interface.inventory.save_to_file(
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NetworkInventory.py", line 291, in save_to_file
    self.get_scans()[index].write_xml(f)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1020, in write_xml
    self._write_hosts(writer)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1101, in _write_hosts
    writer.startElement("address",
  File "../lib/python3.11/xml/sax/saxutils.py", line 170, in startElement
  File "../lib/python3.11/encodings/cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 37-38: character maps to <undefined>

**Comment by dmiller-nmap** [comment]
Duplicate of #2880
