### ISSUE TITLE
?

### ISSUE THREAD

**Issue by ll7790** [nmap/nmap#2980]
Version: 7.95
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\信息搜集\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\App.py", line 286, in run
    window = new_window()
             ^^^^^^^^^^^^
  File "E:\信息搜集\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\App.py", line 129, in new_window
    from zenmapGUI.MainWindow import ScanWindow
  File "E:\信息搜集\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 83, in <module>
    from zenmapGUI.ScanInterface import ScanInterface
  File "E:\信息搜集\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanInterface.py", line 81, in <module>
    from zenmapGUI.ScanToolbar import ScanCommandToolbar, ScanToolbar
  File "E:\信息搜集\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanToolbar.py", line 70, in <module>
    from zenmapGUI.TargetCombo import TargetCombo
  File "E:\信息搜集\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\TargetCombo.py", line 64, in <module>
    from zenmapCore.TargetList import target_list
  File "E:\信息搜集\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\TargetList.py", line 111, in <module>
    target_list = TargetList()
                  ^^^^^^^^^^^^
  File "E:\信息搜集\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\TargetList.py", line 82, in __init__
    t for t in target_file.read().split(";")
               ^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

**Comment by dmiller-nmap** [comment]
Thanks for this report. We believe this issue is fixed in c840e236cb43cfa57d2542a3fc3688807cc90387, which will be included in the next Nmap release.
