### ISSUE TITLE
An Unexpected error has crashed Zenmap

### ISSUE THREAD

**Issue by gufi99** [nmap/nmap#2989]
Version: 7.95
Traceback (most recent call last):
  File "D:\Personal\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 629, in _save_scan_results_cb
    self._save(self.scan_interface, filename, selected, format)
  File "D:\Personal\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 711, in _save
    scan_interface.inventory.save_to_file(
  File "D:\Personal\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NetworkInventory.py", line 291, in save_to_file
    self.get_scans()[index].write_xml(f)
  File "D:\Personal\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1020, in write_xml
    self._write_hosts(writer)
  File "D:\Personal\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1101, in _write_hosts
    writer.startElement("address",
  File "../lib/python3.11/xml/sax/saxutils.py", line 170, in startElement
  File "../lib/python3.11/encodings/cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 37-38: character maps to <undefined>

**Comment by Escape2snap** [comment]
## This might be a similar encoding error.

The issues are caused by encoding and decoding problems in the files, leading to sudden crashes.

## Crash Report

In the directory "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages"

Version: 7.95
Traceback (most recent call last):
  File ".\zenmapGUI\ScriptInterface.py", line 262, in script_list_timer_callback
    callback(True, process)
  File ".\zenmapGUI\ScriptInterface.py", line 271, in initial_script_list_cb
    if status and <u>self.handle_initial_script_list_output(process)</u>:
  File ".\zenmapGUI\ScriptInterface.py", line 302, in handle_initial_script_list_output
    for entry in <u>get_script_entries(</u>
  File ".\zenmapCore\ScriptMetadata.py", line 424, in get_script_entries
    metadata = <u>ScriptMetadata(scripts_dir, nselib_dir)</u>
  File ".\zenmapCore\ScriptMetadata.py", line 287, in __init__
    self.construct_library_arguments()
  File ".\zenmapCore\ScriptMetadata.py", line 417, in construct_library_arguments
    self.library_arguments[libname] = <u>self.get_script_args(filepath)</u>
  File ".\zenmapCore\ScriptMetadata.py", line 363, in get_script_args
    args = <u>ScriptMetadata.get_script_args_from_file</u>(f)
  File ".\zenmapCore\ScriptMetadata.py", line 371, in get_script_args_from_file
    for tag_name, tag_text in nsedoc_tags_iter(f):
  File ".\zenmapCore\ScriptMetadata.py", line 233, in nsedoc_tags_iter
    for line in f:
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode byte 0x93 in position 5665: No mapping for the Unicode character exists in the target code page.

**Comment by Escape2snap** [comment]
The format of the Crash Report is strange after uploading, so I'll put one here.

## Crash Report

***In the directory "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages"***

### Version: 7.95
Traceback (most recent call last):
* File ".\zenmapGUI\ScriptInterface.py", line 262, in script_list_timer_callback
    callback(True, process)
* File ".\zenmapGUI\ScriptInterface.py", line 271, in initial_script_list_cb
    if status and ***self.handle_initial_script_list_output(process)***:
* File ".\zenmapGUI\ScriptInterface.py", line 302, in handle_initial_script_list_output
    for entry in ***get_script_entries(***
* File ".\zenmapCore\ScriptMetadata.py", line 424, in get_script_entries
    metadata = ***ScriptMetadata(scripts_dir, nselib_dir)***
* File ".\zenmapCore\ScriptMetadata.py", line 287, in __init__
    self.construct_library_arguments()
* File ".\zenmapCore\ScriptMetadata.py", line 417, in construct_library_arguments
    self.library_arguments[libname] = ***self.get_script_args(filepath)***
* File ".\zenmapCore\ScriptMetadata.py", line 363, in get_script_args
    args = ***ScriptMetadata.get_script_args_from_file***(f)
* File ".\zenmapCore\ScriptMetadata.py", line 371, in get_script_args_from_file
    for tag_name, tag_text in nsedoc_tags_iter(f):
* File ".\zenmapCore\ScriptMetadata.py", line 233, in nsedoc_tags_iter
    for line in f:
* File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode byte 0x93 in position 5665: No mapping for the Unicode character exists in the target code page.

**Comment by dmiller-nmap** [comment]
Duplicate of #2880
