### ISSUE TITLE
Zenmap : Unicode Encode Error: 'charmap' codec can't encode characters in position 37-38: character maps to <undefined>

### ISSUE THREAD

**Issue by MaxenceTessier** [nmap/nmap#2996]
**In use version**
Zenmap version 7.95

**Describe the bug**
When I try to save a scan as an .xml file, Zenmap crashes regardless of the scan. I have tried with different scans.

**Crash Report**
Version: 7.95
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 629, in _save_scan_results_cb
    self._save(self.scan_interface, filename, selected, format)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 711, in _save
    scan_interface.inventory.save_to_file(
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NetworkInventory.py", line 291, in save_to_file
    self.get_scans()[index].write_xml(f)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1020, in write_xml
    self._write_hosts(writer)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1101, in _write_hosts
    writer.startElement("address",
  File "../lib/python3.11/xml/sax/saxutils.py", line 170, in startElement
  File "../lib/python3.11/encodings/cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 37-38: character maps to <undefined>

**To Reproduce**
Just perform a scan, and when it's finished, go to Scan > Save Scan, choose the .xml file extension, and save it in the Documents folder.

**Expected behavior**
I can normally save my scan as an .xml file.

**Version info (please complete the following information):**
 
| Item | Value |
|--------|--------|
| Version| Windows 11 Pro|
| Version number| 22H2|
| Installation date | 06/‎09/‎2023|
| Operating system version| 22621.2134|
| Experience| Windows Feature Experience Pack 1000.22659.1000.0|

**Comment by jobby889** [comment]
I also get the same error on ZenMap 7.95 on Windows 11 Pro

**Comment by Bernard-J-L** [comment]
Same problem and environment.

Version: 7.95
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 629, in _save_scan_results_cb
    self._save(self.scan_interface, filename, selected, format)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 711, in _save
    scan_interface.inventory.save_to_file(
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NetworkInventory.py", line 291, in save_to_file
    self.get_scans()[index].write_xml(f)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1020, in write_xml
    self._write_hosts(writer)
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\NmapParser.py", line 1101, in _write_hosts
    writer.startElement("address",
  File "../lib/python3.11/xml/sax/saxutils.py", line 170, in startElement
  File "../lib/python3.11/encodings/cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 37-38: character maps to <undefined>

**Comment by dmiller-nmap** [comment]
Believed to be resolved in c840e236cb43cfa57d2542a3fc3688807cc90387, pending release.
