### ISSUE TITLE
Zenmap 7.95 crashes upon startup (Linux).

### ISSUE THREAD

**Issue by synthsncats** [nmap/nmap#2997]
**Describe the bug**
Zenmap crashes upon start with the following crash report:
```
Traceback (most recent call last):
  File "/usr/sbin/zenmap", line 8, in <module>
    sys.exit(run())
             ~~~^^
```
```
  File "/usr/lib/python3.13/site-packages/zenmapGUI/App.py", line 286, in run
    window = new_window()
  File "/usr/lib/python3.13/site-packages/zenmapGUI/App.py", line 130, in new_window
    w = ScanWindow()
  File "/usr/lib/python3.13/site-packages/zenmapGUI/MainWindow.py", line 140, in __init__
    self.scan_interface = ScanInterface()
                          ~~~~~~~~~~~~~^^
```
```
  File "/usr/lib/python3.13/site-packages/zenmapGUI/ScanInterface.py", line 141, in __init__
    self.__create_toolbar()
    ~~~~~~~~~~~~~~~~~~~~~^^
```
```
  File "/usr/lib/python3.13/site-packages/zenmapGUI/ScanInterface.py", line 267, in __create_toolbar
    self.toolbar = ScanToolbar()
                   ~~~~~~~~~~~^^
```
```
  File "/usr/lib/python3.13/site-packages/zenmapGUI/ScanToolbar.py", line 110, in __init__
    self._create_profile()
    ~~~~~~~~~~~~~~~~~~~~^^
```
```
  File "/usr/lib/python3.13/site-packages/zenmapGUI/ScanToolbar.py", line 142, in _create_profile
    self.profile_entry = ProfileCombo()
                         ~~~~~~~~~~~~^^
```
```
  File "/usr/lib/python3.13/site-packages/zenmapGUI/ProfileCombo.py", line 77, in __init__
    self.update()
    ~~~~~~~~~~~^^
```
```
  File "/usr/lib/python3.13/site-packages/zenmapGUI/ProfileCombo.py", line 86, in update
    profile = CommandProfile()
  File "/usr/lib/python3.13/site-packages/zenmapCore/UmitConf.py", line 353, in __init__
    Profile.__init__(self, user_profile)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
```
```
  File "/usr/lib/python3.13/site-packages/zenmapCore/UmitConf.py", line 193, in __init__
    user_profile = Path.scan_profile
                   ^^^^^^^^^^^^^^^^^
```
```
  File "/usr/lib/python3.13/site-packages/zenmapCore/Paths.py", line 146, in __getattr__
    return return_if_exists(
            join(self.user_config_dir, base_paths[name]))
  File "/usr/lib/python3.13/site-packages/zenmapCore/Paths.py", line 205, in return_if_exists
    raise Exception("File '%s' does not exist or could not be found!" % path)
Exception: File '/root/.zenmap/scan_profile.usp' does not exist or could not be found!
```

**To Reproduce:**
open the terminal, type sudo zenmap, and password.
Zenmap crash report pops up automatically.

**Expected behavior:**
Zenmap should start up normally.

**Version info:**
 - OS: Void Linux Vanilla Kernel 6.12.4_1 
 - Zenmap version 7.95
 - Output of `nmap --version`: 7.95

**Additional context:**
N/A

**Comment by synthsncats** [comment]
Zenmap works after a system update.
