### ISSUE TITLE
An unexpected error has crashed Zenmap.

### ISSUE THREAD

**Issue by ji1vzx** [nmap/nmap#2998]
Version: 7.95
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanInterface.py", line 539, in verify_execution
    self.scan_result.refresh_nmap_output()
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanInterface.py", line 909, in refresh_nmap_output
    self.scan_result_notebook.nmap_output.nmap_output.refresh_output()
  File "C:\Program Files (x86)\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\NmapOutputViewer.py", line 288, in refresh_output
    new_output = self.command_execution.stdout_file.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../lib/python3.11/tempfile.py", line 500, in func_wrapper
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

**Comment by dmiller-nmap** [comment]
Duplicate of #2968
