### ISSUE TITLE
zenmap installing issues over python

### ISSUE THREAD

**Issue by peterpt** [nmap/nmap#624]
#:/nmap/zenmap# python setup.py install
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
changing mode of /usr/local/bin/zenmap to 755
running install_data
running install_egg_info
Writing /usr/local/lib/python2.7/site-packages/zenmap-7.40SVN-py2.7.egg-info
Traceback (most recent call last):
  File "setup.py", line 652, in <module>
    setup(**setup_args)
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 249, in run
    self.fix_paths()
  File "setup.py", line 401, in fix_paths
    "CONFIG_DIR": os.path.join(self.saved_prefix, config_dir),
  File "/usr/local/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by Varunram** [comment]
@peterpt This issue seems to have been reported earlier and addressed by @dmiller-nmap in the nmap-dev archives. Link - (http://seclists.org/nmap-dev/2014/q2/315)

> From: Daniel Miller <bonsaiviking () gmail com>
> Date: Tue, 20 May 2014 18:41:38 -0500
> Hello,
> 
> Zenmap's build process currently depends on some actions taken by the
> configure script and the Makefile. I am not surprised that you ended up
> with errors after pulling it out of the Nmap source tree.
> 
> That said, if you have suggestions for how we can be more Pythonic in our
> approach to building and installing our Python programs (Zenmap and Ndiff),
> we welcome your input.
> 
> Thanks,
> Dan

**Comment by fyodor** [comment]
We believe this was resolved some years ago.
