### ISSUE TITLE
Zenmap may incorrectly handle Unicode paths returned by nmap --script-help

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#638]
Reported here: http://seclists.org/nmap-dev/2017/q1/6

```
Version: 7.40
Traceback (most recent call last):
  File "zenmapGUI\ScriptInterface.pyo", line 327, in script_list_timer_callback
  File "zenmapGUI\ScriptInterface.pyo", line 336, in initial_script_list_cb
  File "zenmapGUI\ScriptInterface.pyo", line 368, in handle_initial_script_list_output
  File "zenmapCore\ScriptMetadata.pyo", line 501, in get_script_entries
  File "zenmapCore\ScriptMetadata.pyo", line 355, in __init__
  File "zenmapCore\ScriptMetadata.pyo", line 483, in construct_library_arguments
WindowsError: [Error 3] : u'D:\\360\xbc\xab\xcb\xd9\xe4\xaf\xc0\xc0\xc6\xf7\xcf\xc2\xd4\xd8\\Nmap/nselib/*.*'
```

The path was encoded as GB2312, which nmap --script-help just output as raw bytes. We should probably be using [`sys.getfilesystemencoding()`](https://docs.python.org/2/library/sys.html#sys.getfilesystemencoding), but the docs say that just returns 'mbcs' on Windows. Furthermore, I can't seem to get Nmap to install into such a path in the first place. These are some questions that would have to be answered before we can work on this problem.

**Comment by Varunram** [comment]
@dmiller-nmap If this is limited to the path variable, we could simply use a.decode('utf-8') but my guess is that's not the case here. We might have to investigate all such instances where the output is weird. And is this in anyway related to the problem where the date was not displayed properly?
